name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'
    - name: Install dependencies
      working-directory: ./json-pointy
      run: |
        pwd
        ls -la
        cabal v2-update
        cabal v2-install --only-dependencies --enable-tests
    - name: Build
      working-directory: ./json-pointy
      run: |
        cabal v2-configure --enable-tests
        cabal v2-build
    - name: Run tests
      working-directory: ./json-pointy
      run: cabal test
